export const MODEL_CONSTANTS = {
  USER: 'USER_MODEL',
  EMPLOYEE: 'EMPLOYEE_MODEL',
  STUDENT: 'STUDENT_MODEL',
  EDUCATION: 'EDUCATION_MODEL',
  EXPERIENCE: 'EXPERIENCE_MODEL',
  DONATION: 'DONATION_MODEL',
  FEES:'FEES_MODEL',
  NOTICE: 'NOTICE_MODEL',
  SALARY: 'SALARY_MODEL',
  TIMETABLE: 'TIMETABLE_MODEL'
}

export const VARIABLE_CONSTANTS = {
  SEQUELIZE_CONFIG: 'SEQUELIZE_CONFIG',
  MYSQL: 'mysql',
  AUTO_LOAD_MODULE: true,
  SYNCHRONIZE: true,
  FAILED:'FAILED',
  MESSAGE:"INTERNAL SERVER ERROR"
}

