export const MODEL_CONSTANTS = {
  USER: 'USER_REPOSITORY',
}

export const VARIABLE_CONSTANTS = {
  SEQUELIZE_CONFIG: 'SEQUELIZE_CONFIG',
  MYSQL: 'mysql',
  AUTO_LOAD_MODULE: true,
  SYNCHRONIZE: true
}


